print("Thankyou for purchansing from us ")
print("Enter the products details")
name1 = str(input("enter product 1 name"))
product1 = int(input("Enter the numbers of item"))
price1 = int(input("Enter the price"))
name2 = str(input("enter product 2 name"))
product2 = int(input("enter the numbers of item"))
price2 = int(input("enter the price"))
product1total = (price1*product1)
product2total = (price2*product2)
print(name1 , " total = " , product1total)
print(name2, " total = " , product2total)
allovertotal = (product2total + product1total)
print("Your total bill is =  " , allovertotal)
  