# checking the data type 
X = 20
name = "om"
percentages = 90.0

print(type(X))
print(type(name))
print(type(percentages))
 # type conversions 
 # string to int
age = "20"
age = int(20)
print(age)
print(type(age))
#int to string
age = 20
age = str(20)
print((age))
print(type(age))
# int to float 
age = 20
age = float(20)
print(float(age))


#input taking
age = int(input(("Enter your age")))
print = (age)
print = type(age)
